package com.sha.orbis.model

import android.content.Context
import android.telephony.TelephonyManager
import java.util.Locale

data class CountryCode(
    val isoCode: String,
    val dialCode: String,
    val flagEmoji: String,
    val nameEn: String,
    val nameFr: String,
    val nameAr: String
) {
    fun localizedName(languageCode: String): String = when (languageCode) {
        "fr" -> nameFr
        "ar" -> nameAr
        else -> nameEn
    }

    companion object {
        val ALL_COUNTRIES = listOf(
            CountryCode("DZ", "+213", "🇩🇿", "Algeria", "Algérie", "الجزائر"),
            CountryCode("FR", "+33", "🇫🇷", "France", "France", "فرنسا"),
            CountryCode("MA", "+212", "🇲🇦", "Morocco", "Maroc", "المغرب"),
            CountryCode("TN", "+216", "🇹🇳", "Tunisia", "Tunisie", "تونس"),
            CountryCode("EG", "+20", "🇪🇬", "Egypt", "Égypte", "مصر"),
            CountryCode("SA", "+966", "🇸🇦", "Saudi Arabia", "Arabie Saoudite", "المملكة العربية السعودية"),
            CountryCode("AE", "+971", "🇦🇪", "United Arab Emirates", "Émirats Arabes Unis", "الإمارات العربية المتحدة"),
            CountryCode("QA", "+974", "🇶🇦", "Qatar", "Qatar", "قطر"),
            CountryCode("KW", "+965", "🇰🇼", "Kuwait", "Koweït", "الكويت"),
            CountryCode("OM", "+968", "🇴🇲", "Oman", "Oman", "عمان"),
            CountryCode("BH", "+973", "🇧🇭", "Bahrain", "Bahreïn", "البحرين"),
            CountryCode("JO", "+962", "🇯🇴", "Jordan", "Jordanie", "الأردن"),
            CountryCode("LB", "+961", "🇱🇧", "Lebanon", "Liban", "لبنان"),
            CountryCode("IQ", "+964", "🇮🇶", "Iraq", "Irak", "العراق"),
            CountryCode("LY", "+218", "🇱🇾", "Libya", "Libye", "ليبيا"),
            CountryCode("MR", "+222", "🇲🇷", "Mauritania", "Mauritanie", "موريتانيا"),
            CountryCode("SD", "+249", "🇸🇩", "Sudan", "Soudan", "السودان"),
            CountryCode("PS", "+970", "🇵🇸", "Palestine", "Palestine", "فلسطين"),
            CountryCode("SY", "+963", "🇸🇾", "Syria", "Syrie", "سوريا"),
            CountryCode("YE", "+967", "🇾🇪", "Yemen", "Yémen", "اليمن"),
            CountryCode("TR", "+90", "🇹🇷", "Turkey", "Turquie", "تركيا"),
            CountryCode("US", "+1", "🇺🇸", "United States", "États-Unis", "الولايات المتحدة"),
            CountryCode("CA", "+1", "🇨🇦", "Canada", "Canada", "كندا"),
            CountryCode("GB", "+44", "🇬🇧", "United Kingdom", "Royaume-Uni", "المملكة المتحدة"),
            CountryCode("DE", "+49", "🇩🇪", "Germany", "Allemagne", "ألمانيا"),
            CountryCode("ES", "+34", "🇪🇸", "Spain", "Espagne", "إسبانيا"),
            CountryCode("IT", "+39", "🇮🇹", "Italy", "Italie", "إيطاليا"),
            CountryCode("BE", "+32", "🇧🇪", "Belgium", "Belgique", "بلجيكا"),
            CountryCode("CH", "+41", "🇨🇭", "Switzerland", "Suisse", "سويسرا"),
            CountryCode("SN", "+221", "🇸🇳", "Senegal", "Sénégal", "السنغال"),
            CountryCode("CI", "+225", "🇨🇮", "Ivory Coast", "Côte d'Ivoire", "ساحل العاج"),
            CountryCode("CM", "+237", "🇨🇲", "Cameroon", "Cameroun", "الكاميرون"),
            CountryCode("ML", "+223", "🇲🇱", "Mali", "Mali", "مالي"),
            CountryCode("NE", "+227", "🇳🇪", "Niger", "Niger", "النيجر"),
            CountryCode("AF", "+93", "🇦🇫", "Afghanistan", "Afghanistan", "أفغانستان"),
            CountryCode("AL", "+355", "🇦🇱", "Albania", "Albanie", "ألبانيا"),
            CountryCode("AS", "+1684", "🇦🇸", "American Samoa", "Samoa américaines", "ساموا الأمريكية"),
            CountryCode("AD", "+376", "🇦🇩", "Andorra", "Andorre", "أندورا"),
            CountryCode("AO", "+244", "🇦🇴", "Angola", "Angola", "جمهورية أنغولا"),
            CountryCode("AI", "+1264", "🇦🇮", "Anguilla", "Anguilla", "أنغويلا"),
            CountryCode("AG", "+1268", "🇦🇬", "Antigua and Barbuda", "Antigua-et-Barbuda", "أنتيغوا وباربودا"),
            CountryCode("AR", "+54", "🇦🇷", "Argentina", "Argentine", "الأرجنتين"),
            CountryCode("AM", "+374", "🇦🇲", "Armenia", "Arménie", "أرمينيا"),
            CountryCode("AW", "+297", "🇦🇼", "Aruba", "Aruba", "أروبا"),
            CountryCode("AU", "+61", "🇦🇺", "Australia", "Australie", "أستراليا"),
            CountryCode("AT", "+43", "🇦🇹", "Austria", "Autriche", "النمسا"),
            CountryCode("AZ", "+994", "🇦🇿", "Azerbaijan", "Azerbaïdjan", "أذربيجان"),
            CountryCode("BS", "+1242", "🇧🇸", "Bahamas", "Bahamas", "البهاما"),
            CountryCode("BD", "+880", "🇧🇩", "Bangladesh", "Bangladesh", "بنغلاديش"),
            CountryCode("BB", "+1246", "🇧🇧", "Barbados", "Barbade", "باربادوس"),
            CountryCode("BY", "+375", "🇧🇾", "Belarus", "Biélorussie", "بيلاروسيا"),
            CountryCode("BZ", "+501", "🇧🇿", "Belize", "Belize", "بليز"),
            CountryCode("BJ", "+229", "🇧🇯", "Benin", "Bénin", "بنين"),
            CountryCode("BM", "+1441", "🇧🇲", "Bermuda", "Bermudes", "برمودا"),
            CountryCode("BT", "+975", "🇧🇹", "Bhutan", "Bhoutan", "بوتان"),
            CountryCode("BO", "+591", "🇧🇴", "Bolivia", "Bolivie", "بوليفيا"),
            CountryCode("BA", "+387", "🇧🇦", "Bosnia and Herzegovina", "Bosnie-Herzégovine", "البوسنة والهرسك"),
            CountryCode("BW", "+267", "🇧🇼", "Botswana", "Botswana", "بوتسوانا"),
            CountryCode("BV", "+47", "🇧🇻", "Bouvet Island", "Île Bouvet", "جزر بوفيه"),
            CountryCode("BR", "+55", "🇧🇷", "Brazil", "Brésil", "البرازيل"),
            CountryCode("IO", "+246", "🇮🇴", "British Indian Ocean Territory", "Territoire britannique de l'océan Indien", "إقليم المحيط الهندي البريطاني"),
            CountryCode("VG", "+1284", "🇻🇬", "British Virgin Islands", "Îles Vierges britanniques", "جزر العذراء"),
            CountryCode("BN", "+673", "🇧🇳", "Brunei", "Brunei", "بروناي"),
            CountryCode("BG", "+359", "🇧🇬", "Bulgaria", "Bulgarie", "بلغاريا"),
            CountryCode("BF", "+226", "🇧🇫", "Burkina Faso", "Burkina Faso", "بوركينا فاسو"),
            CountryCode("BI", "+257", "🇧🇮", "Burundi", "Burundi", "بوروندي"),
            CountryCode("KH", "+855", "🇰🇭", "Cambodia", "Cambodge", "كمبوديا"),
            CountryCode("CV", "+238", "🇨🇻", "Cape Verde", "Îles du Cap-Vert", "كابو فيردي"),
            CountryCode("BQ", "+599", "🇧🇶", "Caribbean Netherlands", "Pays-Bas caribéens", "الجزر الكاريبية الهولندية"),
            CountryCode("KY", "+1345", "🇰🇾", "Cayman Islands", "Îles Caïmans", "جزر كايمان"),
            CountryCode("CF", "+236", "🇨🇫", "Central African Republic", "République centrafricaine", "جمهورية أفريقيا الوسطى"),
            CountryCode("TD", "+235", "🇹🇩", "Chad", "Tchad", "تشاد"),
            CountryCode("CL", "+56", "🇨🇱", "Chile", "Chili", "تشيلي"),
            CountryCode("CN", "+86", "🇨🇳", "China", "Chine", "الصين"),
            CountryCode("CX", "+61", "🇨🇽", "Christmas Island", "Île Christmas", "جزيرة كريسماس"),
            CountryCode("CC", "+61", "🇨🇨", "Cocos (Keeling) Islands", "Îles Cocos", "جزر كوكوس"),
            CountryCode("CO", "+57", "🇨🇴", "Colombia", "Colombie", "كولومبيا"),
            CountryCode("KM", "+269", "🇰🇲", "Comoros", "Comores", "جزر القمر"),
            CountryCode("CG", "+242", "🇨🇬", "Congo", "Congo", "جمهورية الكونغو"),
            CountryCode("CK", "+682", "🇨🇰", "Cook Islands", "Îles Cook", "جزر كوك"),
            CountryCode("CR", "+506", "🇨🇷", "Costa Rica", "Costa Rica", "كوستاريكا"),
            CountryCode("HR", "+385", "🇭🇷", "Croatia", "Croatie", "كرواتيا"),
            CountryCode("CU", "+53", "🇨🇺", "Cuba", "Cuba", "كوبا"),
            CountryCode("CW", "+599", "🇨🇼", "Curaçao", "Curaçao", "كوراساو"),
            CountryCode("CY", "+357", "🇨🇾", "Cyprus", "Chypre", "قبرص"),
            CountryCode("CZ", "+420", "🇨🇿", "Czechia", "Tchéquie", "التشيك"),
            CountryCode("CD", "+243", "🇨🇩", "DR Congo", "Congo (Rép. dém.)", "الكونغو"),
            CountryCode("DK", "+45", "🇩🇰", "Denmark", "Danemark", "الدنمارك"),
            CountryCode("DJ", "+253", "🇩🇯", "Djibouti", "Djibouti", "جيبوتي"),
            CountryCode("DM", "+1767", "🇩🇲", "Dominica", "Dominique", "دومينيكا"),
            CountryCode("DO", "+1", "🇩🇴", "Dominican Republic", "République dominicaine", "جمهورية الدومينيكان"),
            CountryCode("EC", "+593", "🇪🇨", "Ecuador", "Équateur", "الإكوادور"),
            CountryCode("SV", "+503", "🇸🇻", "El Salvador", "Salvador", "السلفادور"),
            CountryCode("GQ", "+240", "🇬🇶", "Equatorial Guinea", "Guinée équatoriale", "غينيا الاستوائية"),
            CountryCode("ER", "+291", "🇪🇷", "Eritrea", "Érythrée", "إريتريا"),
            CountryCode("EE", "+372", "🇪🇪", "Estonia", "Estonie", "إستونيا"),
            CountryCode("SZ", "+268", "🇸🇿", "Eswatini", "Eswatini", "إسواتيني"),
            CountryCode("ET", "+251", "🇪🇹", "Ethiopia", "Éthiopie", "إثيوبيا"),
            CountryCode("FK", "+500", "🇫🇰", "Falkland Islands", "Îles Malouines", "جزر فوكلاند"),
            CountryCode("FO", "+298", "🇫🇴", "Faroe Islands", "Îles Féroé", "جزر فارو"),
            CountryCode("FJ", "+679", "🇫🇯", "Fiji", "Fidji", "فيجي"),
            CountryCode("FI", "+358", "🇫🇮", "Finland", "Finlande", "فنلندا"),
            CountryCode("GF", "+594", "🇬🇫", "French Guiana", "Guyane", "غويانا"),
            CountryCode("PF", "+689", "🇵🇫", "French Polynesia", "Polynésie française", "بولينزيا الفرنسية"),
            CountryCode("TF", "+262", "🇹🇫", "French Southern and Antarctic Lands", "Terres australes et antarctiques françaises", "أراض فرنسية جنوبية وأنتارتيكية"),
            CountryCode("GA", "+241", "🇬🇦", "Gabon", "Gabon", "الغابون"),
            CountryCode("GM", "+220", "🇬🇲", "Gambia", "Gambie", "غامبيا"),
            CountryCode("GE", "+995", "🇬🇪", "Georgia", "Géorgie", "جورجيا"),
            CountryCode("GH", "+233", "🇬🇭", "Ghana", "Ghana", "غانا"),
            CountryCode("GI", "+350", "🇬🇮", "Gibraltar", "Gibraltar", "جبل طارق"),
            CountryCode("GR", "+30", "🇬🇷", "Greece", "Grèce", "اليونان"),
            CountryCode("GL", "+299", "🇬🇱", "Greenland", "Groenland", "جرينلاند"),
            CountryCode("GD", "+1473", "🇬🇩", "Grenada", "Grenade", "غرينادا"),
            CountryCode("GP", "+590", "🇬🇵", "Guadeloupe", "Guadeloupe", "غوادلوب"),
            CountryCode("GU", "+1671", "🇬🇺", "Guam", "Guam", "غوام"),
            CountryCode("GT", "+502", "🇬🇹", "Guatemala", "Guatemala", "غواتيمالا"),
            CountryCode("GG", "+44", "🇬🇬", "Guernsey", "Guernesey", "غيرنزي"),
            CountryCode("GN", "+224", "🇬🇳", "Guinea", "Guinée", "غينيا"),
            CountryCode("GW", "+245", "🇬🇼", "Guinea-Bissau", "Guinée-Bissau", "غينيا بيساو"),
            CountryCode("GY", "+592", "🇬🇾", "Guyana", "Guyana", "غيانا"),
            CountryCode("HT", "+509", "🇭🇹", "Haiti", "Haïti", "هايتي"),
            CountryCode("HN", "+504", "🇭🇳", "Honduras", "Honduras", "هندوراس"),
            CountryCode("HK", "+852", "🇭🇰", "Hong Kong", "Hong Kong", "هونغ كونغ"),
            CountryCode("HU", "+36", "🇭🇺", "Hungary", "Hongrie", "المجر"),
            CountryCode("IS", "+354", "🇮🇸", "Iceland", "Islande", "آيسلندا"),
            CountryCode("IN", "+91", "🇮🇳", "India", "Inde", "الهند"),
            CountryCode("ID", "+62", "🇮🇩", "Indonesia", "Indonésie", "إندونيسيا"),
            CountryCode("IR", "+98", "🇮🇷", "Iran", "Iran", "إيران"),
            CountryCode("IE", "+353", "🇮🇪", "Ireland", "Irlande", "أيرلندا"),
            CountryCode("IM", "+44", "🇮🇲", "Isle of Man", "Île de Man", "جزيرة مان"),
            CountryCode("IL", "+972", "🇮🇱", "Israel", "Israël", "إسرائيل"),
            CountryCode("JM", "+1876", "🇯🇲", "Jamaica", "Jamaïque", "جامايكا"),
            CountryCode("JP", "+81", "🇯🇵", "Japan", "Japon", "اليابان"),
            CountryCode("JE", "+44", "🇯🇪", "Jersey", "Jersey", "جيرزي"),
            CountryCode("KZ", "+76", "🇰🇿", "Kazakhstan", "Kazakhstan", "كازاخستان"),
            CountryCode("KE", "+254", "🇰🇪", "Kenya", "Kenya", "كينيا"),
            CountryCode("KI", "+686", "🇰🇮", "Kiribati", "Kiribati", "كيريباتي"),
            CountryCode("XK", "+383", "🇽🇰", "Kosovo", "Kosovo", "كوسوفو"),
            CountryCode("KG", "+996", "🇰🇬", "Kyrgyzstan", "Kirghizistan", "قيرغيزستان"),
            CountryCode("LA", "+856", "🇱🇦", "Laos", "Laos", "لاوس"),
            CountryCode("LV", "+371", "🇱🇻", "Latvia", "Lettonie", "لاتفيا"),
            CountryCode("LS", "+266", "🇱🇸", "Lesotho", "Lesotho", "ليسوتو"),
            CountryCode("LR", "+231", "🇱🇷", "Liberia", "Liberia", "ليبيريا"),
            CountryCode("LI", "+423", "🇱🇮", "Liechtenstein", "Liechtenstein", "ليختنشتاين"),
            CountryCode("LT", "+370", "🇱🇹", "Lithuania", "Lituanie", "ليتوانيا"),
            CountryCode("LU", "+352", "🇱🇺", "Luxembourg", "Luxembourg", "لوكسمبورغ"),
            CountryCode("MO", "+853", "🇲🇴", "Macau", "Macao", "ماكاو"),
            CountryCode("MG", "+261", "🇲🇬", "Madagascar", "Madagascar", "مدغشقر"),
            CountryCode("MW", "+265", "🇲🇼", "Malawi", "Malawi", "مالاوي"),
            CountryCode("MY", "+60", "🇲🇾", "Malaysia", "Malaisie", "ماليزيا"),
            CountryCode("MV", "+960", "🇲🇻", "Maldives", "Maldives", "المالديف"),
            CountryCode("MT", "+356", "🇲🇹", "Malta", "Malte", "مالطا"),
            CountryCode("MH", "+692", "🇲🇭", "Marshall Islands", "Îles Marshall", "جزر مارشال"),
            CountryCode("MQ", "+596", "🇲🇶", "Martinique", "Martinique", "مارتينيك"),
            CountryCode("MU", "+230", "🇲🇺", "Mauritius", "Île Maurice", "موريشيوس"),
            CountryCode("YT", "+262", "🇾🇹", "Mayotte", "Mayotte", "مايوت"),
            CountryCode("MX", "+52", "🇲🇽", "Mexico", "Mexique", "المسكيك"),
            CountryCode("FM", "+691", "🇫🇲", "Micronesia", "Micronésie", "ميكرونيسيا"),
            CountryCode("MD", "+373", "🇲🇩", "Moldova", "Moldavie", "مولدوڤا"),
            CountryCode("MC", "+377", "🇲🇨", "Monaco", "Monaco", "موناكو"),
            CountryCode("MN", "+976", "🇲🇳", "Mongolia", "Mongolie", "منغوليا"),
            CountryCode("ME", "+382", "🇲🇪", "Montenegro", "Monténégro", "الجبل الاسود"),
            CountryCode("MS", "+1664", "🇲🇸", "Montserrat", "Montserrat", "مونتسرات"),
            CountryCode("MZ", "+258", "🇲🇿", "Mozambique", "Mozambique", "موزمبيق"),
            CountryCode("MM", "+95", "🇲🇲", "Myanmar", "Birmanie", "ميانمار"),
            CountryCode("NA", "+264", "🇳🇦", "Namibia", "Namibie", "ناميبيا"),
            CountryCode("NR", "+674", "🇳🇷", "Nauru", "Nauru", "ناورو"),
            CountryCode("NP", "+977", "🇳🇵", "Nepal", "Népal", "نيبال"),
            CountryCode("NL", "+31", "🇳🇱", "Netherlands", "Pays-Bas", "هولندا"),
            CountryCode("NC", "+687", "🇳🇨", "New Caledonia", "Nouvelle-Calédonie", "كاليدونيا الجديدة"),
            CountryCode("NZ", "+64", "🇳🇿", "New Zealand", "Nouvelle-Zélande", "نيوزيلندا"),
            CountryCode("NI", "+505", "🇳🇮", "Nicaragua", "Nicaragua", "نيكاراغوا"),
            CountryCode("NG", "+234", "🇳🇬", "Nigeria", "Nigéria", "نيجيريا"),
            CountryCode("NU", "+683", "🇳🇺", "Niue", "Niue", "نييوي"),
            CountryCode("NF", "+672", "🇳🇫", "Norfolk Island", "Île Norfolk", "جزيرة نورفولك"),
            CountryCode("KP", "+850", "🇰🇵", "North Korea", "Corée du Nord", "كوريا الشمالية"),
            CountryCode("MK", "+389", "🇲🇰", "North Macedonia", "Macédoine du Nord", "شمال مقدونيا"),
            CountryCode("MP", "+1670", "🇲🇵", "Northern Mariana Islands", "Îles Mariannes du Nord", "جزر ماريانا الشمالية"),
            CountryCode("NO", "+47", "🇳🇴", "Norway", "Norvège", "النرويج"),
            CountryCode("PK", "+92", "🇵🇰", "Pakistan", "Pakistan", "باكستان"),
            CountryCode("PW", "+680", "🇵🇼", "Palau", "Palaos (Palau)", "بالاو"),
            CountryCode("PA", "+507", "🇵🇦", "Panama", "Panama", "بنما"),
            CountryCode("PG", "+675", "🇵🇬", "Papua New Guinea", "Papouasie-Nouvelle-Guinée", "بابوا غينيا الجديدة"),
            CountryCode("PY", "+595", "🇵🇾", "Paraguay", "Paraguay", "باراغواي"),
            CountryCode("PE", "+51", "🇵🇪", "Peru", "Pérou", "بيرو"),
            CountryCode("PH", "+63", "🇵🇭", "Philippines", "Philippines", "الفلبين"),
            CountryCode("PN", "+64", "🇵🇳", "Pitcairn Islands", "Îles Pitcairn", "جزر بيتكيرن"),
            CountryCode("PL", "+48", "🇵🇱", "Poland", "Pologne", "بولندا"),
            CountryCode("PT", "+351", "🇵🇹", "Portugal", "Portugal", "البرتغال"),
            CountryCode("PR", "+1", "🇵🇷", "Puerto Rico", "Porto Rico", "بويرتوريكو"),
            CountryCode("RO", "+40", "🇷🇴", "Romania", "Roumanie", "رومانيا"),
            CountryCode("RU", "+73", "🇷🇺", "Russia", "Russie", "روسيا"),
            CountryCode("RW", "+250", "🇷🇼", "Rwanda", "Rwanda", "رواندا"),
            CountryCode("RE", "+262", "🇷🇪", "Réunion", "Réunion", "لا ريونيون"),
            CountryCode("BL", "+590", "🇧🇱", "Saint Barthélemy", "Saint-Barthélemy", "سان بارتليمي"),
            CountryCode("SH", "+290", "🇸🇭", "Saint Helena, Ascension and Tristan da Cunha", "Sainte-Hélène, Ascension et Tristan da Cunha", "سانت هيلينا وأسينشين وتريستان دا كونا"),
            CountryCode("KN", "+1869", "🇰🇳", "Saint Kitts and Nevis", "Saint-Christophe-et-Niévès", "سانت كيتس ونيفيس"),
            CountryCode("LC", "+1758", "🇱🇨", "Saint Lucia", "Sainte-Lucie", "سانت لوسيا"),
            CountryCode("MF", "+590", "🇲🇫", "Saint Martin", "Saint-Martin", "سانت مارتن"),
            CountryCode("PM", "+508", "🇵🇲", "Saint Pierre and Miquelon", "Saint-Pierre-et-Miquelon", "سان بيير وميكلون"),
            CountryCode("VC", "+1784", "🇻🇨", "Saint Vincent and the Grenadines", "Saint-Vincent-et-les-Grenadines", "سانت فينسنت والغرينادين"),
            CountryCode("WS", "+685", "🇼🇸", "Samoa", "Samoa", "ساموا"),
            CountryCode("SM", "+378", "🇸🇲", "San Marino", "Saint-Marin", "سان مارينو"),
            CountryCode("RS", "+381", "🇷🇸", "Serbia", "Serbie", "صيربيا"),
            CountryCode("SC", "+248", "🇸🇨", "Seychelles", "Seychelles", "سيشل"),
            CountryCode("SL", "+232", "🇸🇱", "Sierra Leone", "Sierra Leone", "سيراليون"),
            CountryCode("SG", "+65", "🇸🇬", "Singapore", "Singapour", "سنغافورة"),
            CountryCode("SX", "+1721", "🇸🇽", "Sint Maarten", "Saint-Martin", "سينت مارتن"),
            CountryCode("SK", "+421", "🇸🇰", "Slovakia", "Slovaquie", "سلوفاكيا"),
            CountryCode("SI", "+386", "🇸🇮", "Slovenia", "Slovénie", "سلوفينيا"),
            CountryCode("SB", "+677", "🇸🇧", "Solomon Islands", "Îles Salomon", "جزر سليمان"),
            CountryCode("SO", "+252", "🇸🇴", "Somalia", "Somalie", "الصومال"),
            CountryCode("ZA", "+27", "🇿🇦", "South Africa", "Afrique du Sud", "جنوب أفريقيا"),
            CountryCode("GS", "+500", "🇬🇸", "South Georgia", "Géorgie du Sud-et-les Îles Sandwich du Sud", "جورجيا الجنوبية"),
            CountryCode("KR", "+82", "🇰🇷", "South Korea", "Corée du Sud", "كوريا الجنوبية"),
            CountryCode("SS", "+211", "🇸🇸", "South Sudan", "Soudan du Sud", "جنوب السودان"),
            CountryCode("LK", "+94", "🇱🇰", "Sri Lanka", "Sri Lanka", "سريلانكا"),
            CountryCode("SR", "+597", "🇸🇷", "Suriname", "Surinam", "سورينام"),
            CountryCode("SJ", "+4779", "🇸🇯", "Svalbard and Jan Mayen", "Svalbard et Jan Mayen", "سفالبارد ويان ماين"),
            CountryCode("SE", "+46", "🇸🇪", "Sweden", "Suède", "السويد"),
            CountryCode("ST", "+239", "🇸🇹", "São Tomé and Príncipe", "São Tomé et Príncipe", "ساو تومي وبرينسيب"),
            CountryCode("TW", "+886", "🇹🇼", "Taiwan", "Taïwan", "تايوان"),
            CountryCode("TJ", "+992", "🇹🇯", "Tajikistan", "Tadjikistan", "طاجيكستان"),
            CountryCode("TZ", "+255", "🇹🇿", "Tanzania", "Tanzanie", "تنزانيا"),
            CountryCode("TH", "+66", "🇹🇭", "Thailand", "Thaïlande", "تايلند"),
            CountryCode("TL", "+670", "🇹🇱", "Timor-Leste", "Timor oriental", "تيمور الشرقية"),
            CountryCode("TG", "+228", "🇹🇬", "Togo", "Togo", "توغو"),
            CountryCode("TK", "+690", "🇹🇰", "Tokelau", "Tokelau", "توكيلاو"),
            CountryCode("TO", "+676", "🇹🇴", "Tonga", "Tonga", "تونغا"),
            CountryCode("TT", "+1868", "🇹🇹", "Trinidad and Tobago", "Trinité-et-Tobago", "ترينيداد وتوباغو"),
            CountryCode("TM", "+993", "🇹🇲", "Turkmenistan", "Turkménistan", "تركمانستان"),
            CountryCode("TC", "+1649", "🇹🇨", "Turks and Caicos Islands", "Îles Turques-et-Caïques", "جزر توركس وكايكوس"),
            CountryCode("TV", "+688", "🇹🇻", "Tuvalu", "Tuvalu", "توفالو"),
            CountryCode("UG", "+256", "🇺🇬", "Uganda", "Ouganda", "أوغندا"),
            CountryCode("UA", "+380", "🇺🇦", "Ukraine", "Ukraine", "أوكرانيا"),
            CountryCode("UM", "+268", "🇺🇲", "United States Minor Outlying Islands", "Îles mineures éloignées des États-Unis", "جزر الولايات المتحدة الصغيرة النائية"),
            CountryCode("VI", "+1340", "🇻🇮", "United States Virgin Islands", "Îles Vierges des États-Unis", "جزر العذراء الامريكية"),
            CountryCode("UY", "+598", "🇺🇾", "Uruguay", "Uruguay", "الأوروغواي"),
            CountryCode("UZ", "+998", "🇺🇿", "Uzbekistan", "Ouzbékistan", "أوزباكستان"),
            CountryCode("VU", "+678", "🇻🇺", "Vanuatu", "Vanuatu", "فانواتو"),
            CountryCode("VA", "+39", "🇻🇦", "Vatican City", "Cité du Vatican", "مدينة الفاتيكان"),
            CountryCode("VE", "+58", "🇻🇪", "Venezuela", "Venezuela", "فنزويلا"),
            CountryCode("VN", "+84", "🇻🇳", "Vietnam", "Viêt Nam", "فيتنام"),
            CountryCode("WF", "+681", "🇼🇫", "Wallis and Futuna", "Wallis-et-Futuna", "واليس وفوتونا"),
            CountryCode("EH", "+212", "🇪🇭", "Western Sahara", "Sahara Occidental", "الصحراء الغربية"),
            CountryCode("ZM", "+260", "🇿🇲", "Zambia", "Zambie", "زامبيا"),
            CountryCode("ZW", "+263", "🇿🇼", "Zimbabwe", "Zimbabwe", "زيمبابوي"),
            CountryCode("AX", "+35818", "🇦🇽", "Åland Islands", "Ahvenanmaa", "جزر أولاند"),
        )

        fun defaultCountry(context: Context): CountryCode {
            val telephonyManager = context.getSystemService(Context.TELEPHONY_SERVICE) as? TelephonyManager
            val simIso = telephonyManager?.simCountryIso?.trim()?.uppercase(Locale.ROOT)
            val networkIso = telephonyManager?.networkCountryIso?.trim()?.uppercase(Locale.ROOT)
            val localeIso = Locale.getDefault().country.uppercase(Locale.ROOT)

            val detectedIso = when {
                !simIso.isNullOrBlank() -> simIso
                !networkIso.isNullOrBlank() -> networkIso
                localeIso.isNotBlank() -> localeIso
                else -> "DZ"
            }

            return ALL_COUNTRIES.find { it.isoCode.equals(detectedIso, ignoreCase = true) }
                ?: ALL_COUNTRIES.find { it.isoCode == "DZ" }
                ?: ALL_COUNTRIES.first()
        }

        fun findByIso(iso: String): CountryCode? =
            ALL_COUNTRIES.find { it.isoCode.equals(iso.trim(), ignoreCase = true) }

        fun findByDialCode(dialCode: String): CountryCode? {
            val clean = if (dialCode.startsWith("+")) dialCode.trim() else "+" + dialCode.trim()
            return ALL_COUNTRIES.find { it.dialCode == clean }
        }
    }
}
